### ISSUE TITLE
Buffertools issue when doing npm install of the package

### ISSUE THREAD

**Issue by yiweiang** [DexterInd/GoPiGo#132]
Encountering this issue when I try to install this package.

```
make: Leaving directory '/home/pi/Documents/repos/robot/node_modules/buffertools/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/v0.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:784:12)
gyp ERR! System Linux 4.1.7+
gyp ERR! command "node" "/home/pi/.nvm/v0.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/Documents/repos/robot/node_modules/buffertools
gyp ERR! node -v v0.11.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
robot@0.0.0 /home/pi/Documents/repos/robot
└── (empty)

npm ERR! Linux 4.1.7+
npm ERR! argv "node" "/home/pi/.nvm/v0.11.1/bin/npm" "install" "node-gopigo"
npm ERR! node v0.11.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! buffertools@2.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@2.1.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buffertools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Documents/repos/robot/npm-debug.log
```

**Comment by marcellobarile** [comment]
hi @yiweiang,
looking your logs the error seems to be related to an old version of Node.js:

```
gyp ERR! cwd /home/pi/Documents/repos/robot/node_modules/buffertools
gyp ERR! node -v v0.11.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

Could you try updating your Node.js and NPM softwares?

Thank you and have a nice day
