### ISSUE TITLE
C# Library exceptions

### ISSUE THREAD

**Issue by muziekklas** [DexterInd/GoPiGo#184]
We are experimenting for a hackaton with the GoPiGo and Raspi 3.
We installed the latest and greatest Windows 10 IOT on the Pi and try to run this simple background task we made:
`C#
            _goPiGo.MotorController().Stop();
            try{ 
                System.Diagnostics.Debug.WriteLine(Sensor.MeasureInCentimeters());
            }catch(Exception e)
            {
                System.Diagnostics.Debug.WriteLine("[ERR]:" + e.ToString() + "\n");
            }
`

The Exception is the following:
Unexpected number of bytes was transferred. Expected: '. Actual: '.
   at Windows.Devices.I2c.I2cDevice.Write(Byte[] buffer)
   at GoPiGo.Sensors.UltrasonicRangerSensor.MeasureInCentimeters()
   at BackDriveme.StartupTask.RandomMovement()

Also when we set the motor direction, it sometimes shoots a FileNotFoundException. 

Also how "Up-To-Date" and bug-free is the library? Is it compatible with the latest Windows IOT, Raspi3 and the GoPiGo 2 board?

**Comment by muziekklas** [comment]
the filenotfound exception: 
[ERR]:System.IO.FileNotFoundException: The system cannot find the file specified.

**Comment by muziekklas** [comment]
I am reworking the C# library for Mono (https://github.com/muziekklas/GoPiGo.mono) which already seem to work and for the WinIOT, which is still buggy: https://github.com/muziekklas/GoPiGo.Net
Feel free to contribute!
