### ISSUE TITLE
Flask Server

### ISSUE THREAD

**Issue by hankp46** [DexterInd/GoPiGo#251]
When attempting to run flask server for Alexabot get following messages;
Have no idea on how to resolve

python alexabot-flask-app.py
 * Running on http://0.0.0.0:5000/
Traceback (most recent call last):
  File "alexabot-flask-app.py", line 73, in <module>
    app.run(debug=True, host='0.0.0.0')
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 706, in run_simple
    test_socket.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by DexterInd** [comment]
Going to assume this was resolved, right?  :-)

**Comment by hankp46** [comment]
N

**Comment by hankp46** [comment]
Resolved socket error. But still can't get trigger to work. Posted full problem on Dexter forum under General Discussions. Any suggestions appreciated.
